# services:
#  service:
#    image: <service-name>:latest
#    restart: unless-stopped
#    volumes:
#      - ./service/:/app/
#      - output:/tmp/output/
#      - models:/tmp/models/
#      - data:/tmp/data/
#    ports:
#      - ${STREAMLIT_RUN_PORT}:${STREAMLIT_RUN_PORT}
#    env_file:
#      - ./.env
#
#volumes:
#  output:
#  models:
#  data:

services:
  service:
    build: /home/username/TNVED
    ports:
      - 8505:8501
